//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajat
    {
        public int ID { get; set; }
        public int MagazinID { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public decimal CNP { get; set; }
        public string Email { get; set; }
        public string Parola { get; set; }
        public System.DateTime DataAngajare { get; set; }
        public int Salariu { get; set; }
        public string Functie { get; set; }
    
        public virtual Magazin Magazin { get; set; }
    }
}
