//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livrare
    {
        public int ID { get; set; }
        public int FurnizorID { get; set; }
        public int MagazinID { get; set; }
        public System.DateTime DataSolicitare { get; set; }
        public Nullable<System.DateTime> DataLivrare { get; set; }
        public string Status { get; set; }
        public string Descriere { get; set; }
        public int Pret { get; set; }
    
        public virtual Furnizor Furnizor { get; set; }
        public virtual Magazin Magazin { get; set; }
    }
}
