//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produs
    {
        public int ID { get; set; }
        public int CategorieID { get; set; }
        public int MagazinID { get; set; }
        public string Denumire { get; set; }
        public string Greutate { get; set; }
        public Nullable<double> Pret { get; set; }
        public int Cantitate { get; set; }
        public Nullable<System.DateTime> DataExpirate { get; set; }
        public string Descriere { get; set; }
        public string Imagine { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Magazin Magazin { get; set; }
    }
}
